---
# Synopsis: Suppress rules that will not be handled
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: msft.Generic.IgnoreRule
spec:
  rule:
    - Azure.Storage.UseReplication
    - Azure.Storage.SoftDelete
    - Azure.Storage.ContainerSoftDelete
    - Azure.Storage.Firewall
  if:
    type: '.'
    in:
      - 'Microsoft.Storage/storageAccounts'

---
# Synopsis: Azure resource must have an valid env tag set.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: msft.Azure.Tags
spec:
  with:
    - PSRule.Rules.Azure\Azure.Resource.SupportsTags
  condition:
    allOf:
      - in:
          - 'prd'
          - 'tst'
          - 'dev'
          - 'acc'
        field: 'tags.environment'
