
---
# Synopsis: Storage account names need to be between 3 and 24 characters long and start with 'st'.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: msft.FunctionApp.NameConvention
spec:
  type:
  - Microsoft.web/sites
  condition:
    allOf:
      - name: '.'
        startsWith: 'azfunc-'