trigger:
  paths:
    exclude:
      - .pipelines
      - .ps-rule
    include:
      - bicep

stages:
  - template: templates/infrastructure.yml
    parameters:
      build: true
      documentation: false
      psrule: true
      msado: true
      serviceconnection: ''